"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['snakeGame.py']
DATA_FILES = ['apple.png', 'laser5.ogg', 'Saito_Koji_-_08_-_One_Minute_For_The_Sun.ogg', 'snake.png', 'snakebot.png','snakelogo.png', 'test.png']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
